# This is a GoReleaser configuration file
# For more details, visit: https://goreleaser.com

# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj

version: 2

project_name: clyde

env:
  - SRC=github.com/{{.Env.GITHUB_REPOSITORY_OWNER}}/{{.ProjectName}}

# Snapshot configuration for dev builds
snapshot:
  version_template: "{{incpatch .Version}}-next"

before:
  hooks:
    - go mod tidy
    - echo "{{.Env.SRC}} -- {{.Version}}"

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    binary: "{{.ProjectName}}"
    flags:
      - -trimpath
    ldflags:
      - -s -w
      - -X {{.Env.SRC}}/cmd.date={{.Date}}
      - -X {{.Env.SRC}}/cmd.revision={{.ShortCommit}}
      - -X {{.Env.SRC}}/cmd.version=v{{.Version}}

archives:
  - formats: [tar.gz]
    # this name template makes the OS and Arch compatible with the results of `uname`.
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    # use zip for windows archives
    format_overrides:
      - goos: windows
        formats: [zip]
    files:
      - LICENSE
      - README.md

checksum:
  name_template: "{{.ProjectName}}_{{.Version}}_checksums.txt"
  algorithm: sha256

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
      - Merge pull request
      - Merge branch

# Source archive configuration
source:
  enabled: true
  name_template: "{{.ProjectName}}_{{.Version}}_source"
  format: "tar.gz"

release:
  github:
    owner: "{{.Env.GITHUB_REPOSITORY_OWNER}}"
    name: "{{.ProjectName}}"
  prerelease: auto
  draft: false
  name_template: "{{.ProjectName}} v{{.Version}}"
  footer: >-

    ---

    Released by [GoReleaser](https://github.com/goreleaser/goreleaser).

# Social media announcment - no, not at the moment
# https://goreleaser.com/customization/announce/
announce:
  skip: true

# Homebrew tap configuration
brews:
  - name: "{{.ProjectName}}"
    homepage: "https://{{.Env.SRC}}/"
    description: "Terminal-based UI for monitoring Project Calico network flows in real-time"
    license: "Apache-2.0"
    skip_upload: auto
    directory: Formula
    download_strategy: CurlDownloadStrategy

    install: |
      bin.install "{{.ProjectName}}"

    test: |
      assert_match "v{{.Version}}", shell_output("#{bin}/{{.ProjectName}} version")

    repository:
      owner: "{{.Env.GITHUB_REPOSITORY_OWNER}}"
      name: homebrew-tap
      branch: main
      token: "{{.Env.GITHUB_TOKEN}}"

    # Commit author
    commit_author:
      name: GoReleaser Bot
      email: bot@goreleaser.com

    # Custom commit message
    commit_msg_template: "Brew formula update for {{.ProjectName}} version {{.Version}}"
