# .github/workflows/homebrew-release.yml
name: homebrew-release

on:
  release:
    types: [released]

jobs:
  homebrew-release:
    runs-on: ubuntu-latest
    steps:
      - name: Update Homebrew formula
        uses: dawidd6/action-homebrew-bump-formula@v5
        with:
          # Required, custom GitHub access token with the 'public_repo' and 'workflow' scopes
          token: ${{ secrets.GORELEASER_GH_TOKEN }}
          # # Optional, will commit with this user name
          # user_name: name
          # # Optional, will commit with this user email
          # user_email: email@example.com
          # Optional, will create tap repo fork in organization
          # org: ORG
          # Optional, use the origin repository instead of forking
          no_fork: false
          # Optional, defaults to homebrew/core
          tap: doucol/homebrew-tap
          # Formula name, required
          formula: clyde
          # Optional, will be determined automatically
          # tag: ${{github.ref}}
          # # Optional, will be determined automatically
          # revision: ${{github.sha}}
          # Optional, if don't want to check for already open PRs
          force: false # true

